# Generated by Django 4.2 on 2026-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Paste an external banner image URL here', max_length=500, null=True)),
                ('link', models.CharField(blank=True, help_text='Where should this banner lead to? (Optional)', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
